
// Dummy data for tasks
export const dummyTasks= [
    {
      id: 1,
      title: 'Implement new feature in React Native app',
      description: 'Develop new feature for the company\'s React Native mobile application.',
      creator: 'Ivan Cliff',
      createdAt: '1 minute ago',
      dueDate: '12/05/2023',
      reward: 'UGX 120,000',
      complexity: 'Medium',
    },
    {
      id: 2,
      title: 'Design UI for new dashboard',
      description: 'Create a modern and intuitive user interface for the analytics dashboard.',
      creator: 'Sarah Lee',
      createdAt: '30 minutes ago',
      dueDate: '15/05/2023',
      reward: 'UGX 80,000',
      complexity: 'High',
    },
    {
      id: 3,
      title: 'Optimize database queries',
      description: 'Improve the performance of key database queries to reduce load times.',
      creator: 'Mike Johnson',
      createdAt: '2 hours ago',
      dueDate: '18/05/2023',
      reward: 'UGX 100,000',
      complexity: 'High',
    },
    {
      id: 4,
      title: 'Implement user authentication',
      description: 'Set up secure user authentication system using OAuth 2.0.',
      creator: 'Emily Chen',
      createdAt: '1 day ago',
      dueDate: '20/05/2023',
      reward: 'UGX 90,000',
      complexity: 'Medium',
    },
    {
      id: 5,
      title: 'Create API documentation',
      description: 'Write comprehensive documentation for the new API endpoints.',
      creator: 'Alex Turner',
      createdAt: '2 days ago',
      dueDate: '25/05/2023',
      reward: 'UGX 70,000',
      complexity: 'Low',
    },
    {
      id: 6,
      title: 'Implement real-time chat feature',
      description: 'Add a real-time chat functionality to the existing web application.',
      creator: 'Lisa Wang',
      createdAt: '3 days ago',
      dueDate: '30/05/2023',
      reward: 'UGX 150,000',
      complexity: 'High',
    },
  ]
  